SET (AMBF_CLIENT_FOUND FALSE)


UNSET( AMBF_CLIENT_INCLUDE_DIR              CACHE)   
UNSET( AMBF_CLIENT_LIBRARY                  CACHE)  


get_filename_component(PARENT_CMAKE ../cmake ABSOLUTE)
set (CMAKE_MODULE_PATH ${PARENT_CMAKE} )

FIND_PATH (AMBF_CLIENT_INCLUDE_DIR ambf_client/ambf_client.h
HINTS
$ENV{HOME}/ambf/ambf_ros_modules/ambf_client/include
/usr/local/include
/usr/include
)

FIND_LIBRARY (AMBF_CLIENT_LIBRARY ambf_client
PATHS
$ENV{HOME}/ambf/build/devel/lib
)

IF (AMBF_CLIENT_INCLUDE_DIR AND AMBF_CLIENT_LIBRARY)
  SET (AMBF_CLIENT_FOUND TRUE)
ELSE(AMBF_CLIENT_INCLUDE_DIR AND AMBF_CLIENT_LIBRARY)   
  SET (AMBF_CLIENT_FOUND FALSE) 
  MESSAGE (SEND_ERROR " Could not find AMBF_CLIENT.")
ENDIF (RBDL_INCLUDE_DIR AND RBDL_LIBRARY)

IF (AMBF_CLIENT_FOUND)
    MESSAGE(STATUS "Found AMBF: ${AMBF_CLIENT_LIBRARY}")
ELSE(AMBF_CLIENT_FOUND)
    MESSAGE(STATUS " NOt Found AMBF")
ENDIF (RBDL_FOUND)